import { Light, register } from '@antv/g2';

const theme = {
  padding: 'auto',
  margin: 16,
  size: 1,
  color: 'rgba(22, 119, 255, 1)',
  category10: [
    '#1677ff',
    '#15e7e4',
    '#8954FC',
    '#F45BB5',
    '#00A6FF',
    '#33E59B',
    '#D666E4',
    '#6151FF',
    '#BF3C93',
    '#005EE0',
  ],
  category20: [
    'rgba(22, 119, 255, 1)',
    'rgba(21, 231, 228, 1)',
    'rgba(244, 91, 181, 1)',
    '#D580FF',
    'rgba(0, 166, 255, 1)',
    '#60C42D',
    '#BD8F24',
    '#FF80CA',
    '#2491B3',
    '#17C76F',
    '#AABA01',
    '#BC7CFC',
    '#237CBC',
    '#2DE379',
    '#CE8032',
    '#FF7AF4',
    '#545FD3',
    '#AFE410',
    '#D8C608',
    '#FFA1E0',
  ],
  enter: { duration: 300, fill: 'both', delay: 0 },
  update: { duration: 300, fill: 'both', delay: 0 },
  exit: { duration: 300, fill: 'both', delay: 0 },
  view: {
    viewFill: 'transparent',
    plotFill: 'transparent',
    mainFill: 'transparent',
    contentFill: 'transparent',
  },
  line: {
    line: { fill: '', strokeOpacity: 1, lineWidth: 1, lineCap: 'round' },
  },
  point: {
    point: { r: 3, fillOpacity: 0.95, lineWidth: 0 },
    hollow: { r: 3, strokeOpacity: 0.95, lineWidth: 1 },
    plus: { r: 3, strokeOpacity: 0.95, lineWidth: 3 },
    diamond: { r: 3, strokeOpacity: 0.95, lineWidth: 1 },
  },
  interval: {
    rect: { fillOpacity: 0.95 },
    hollow: { fill: '', strokeOpacity: 1, lineWidth: 2 },
  },
  area: { area: { fillOpacity: 0.85, lineWidth: 0 } },
  polygon: { polygon: { fillOpacity: 0.95 } },
  cell: {
    cell: { fillOpacity: 0.95 },
    hollow: { fill: '', strokeOpacity: 1, lineWidth: 2 },
  },
  rect: {
    rect: { fillOpacity: 0.95 },
    hollow: { fill: '', strokeOpacity: 1, lineWidth: 2 },
  },
  link: { link: { fill: '', strokeOpacity: 1 } },
  vector: { vector: { fillOpacity: 1 } },
  box: { box: { fillOpacity: 0.95, stroke: '#1D2129', lineWidth: 1 } },
  text: {
    text: {
      fill: '#1D2129',
      fontSize: 12,
      lineWidth: 0,
      connectorStroke: '#416180',
      connectorStrokeOpacity: 0.45,
      connectorLineWidth: 1,
      backgroundFill: '#416180',
      backgroundFillOpacity: 0.15,
      backgroundPadding: [2, 4],
      startMarkerSymbol: 'circle',
      startMarkerSize: 4,
      endMarkerSymbol: 'circle',
      endMarkerSize: 4,
    },
    badge: {
      fill: '#1D2129',
      fillOpacity: 0.65,
      lineWidth: 0,
      fontSize: 10,
      textAlign: 'center',
      textBaseline: 'middle',
      markerFill: '#416180',
      markerFillOpacity: 0.25,
      markerStrokeOpacity: 0,
    },
  },
  lineX: { line: { stroke: '#416180', strokeOpacity: 0.45, lineWidth: 1 } },
  lineY: { line: { stroke: '#416180', strokeOpacity: 0.45, lineWidth: 1 } },
  rangeX: { range: { fill: '#416180', fillOpacity: 0.15, lineWidth: 0 } },
  rangeY: { range: { fill: '#416180', fillOpacity: 0.15, lineWidth: 0 } },
  connector: {
    connector: {
      stroke: '#416180',
      strokeOpacity: 0.45,
      lineWidth: 1,
      connectLength1: 12,
      endMarker: true,
      endMarkerSize: 6,
      endMarkerFill: '#416180',
      endMarkerFillOpacity: 0.95,
    },
  },
  axis: {
    arrow: false,
    gridLineDash: [3, 4],
    gridLineWidth: 0.5,
    gridStroke: '#1D2129',
    gridStrokeOpacity: 0.1,
    labelAlign: 'horizontal',
    labelFill: '#1D2129',
    labelOpacity: 0.45,
    labelFontSize: 12,
    labelFontWeight: 'normal',
    labelSpacing: 8,
    line: false,
    lineLineWidth: 0.5,
    lineStroke: '#1D2129',
    lineStrokeOpacity: 0.45,
    tickLength: 4,
    tickLineWidth: 1,
    tickStroke: '#1D2129',
    tickOpacity: 0.45,
    titleFill: '#1D2129',
    titleOpacity: 0.9,
    titleFontSize: 12,
    titleFontWeight: 'normal',
    titleSpacing: 12,
    titleTransformOrigin: 'center',
    lineArrowOffset: 6,
    lineArrowSize: 6,
  },
  axisTop: {
    gridDirection: 'positive',
    labelDirection: 'negative',
    tickDirection: 'negative',
    titlePosition: 'top',
    titleSpacing: 12,
    labelSpacing: 4,
    titleTextBaseline: 'middle',
  },
  axisBottom: {
    gridDirection: 'negative',
    labelDirection: 'positive',
    tickDirection: 'positive',
    titlePosition: 'bottom',
    titleSpacing: 12,
    labelSpacing: 4,
    titleTextBaseline: 'bottom',
    titleTransform: 'translate(0, 8)',
  },
  axisLeft: {
    gridDirection: 'positive',
    labelDirection: 'negative',
    labelSpacing: 4,
    tickDirection: 'negative',
    titlePosition: 'left',
    titleSpacing: 12,
    titleTextBaseline: 'middle',
    titleDirection: 'vertical',
    titleTransform: 'rotate(-90) translate(0, -8)',
    titleTransformOrigin: 'center',
  },
  axisRight: {
    gridDirection: 'negative',
    labelDirection: 'positive',
    labelSpacing: 4,
    tickDirection: 'positive',
    titlePosition: 'right',
    titleSpacing: 12,
    titleTextBaseline: 'top',
    titleDirection: 'vertical',
    titleTransformOrigin: 'center',
  },
  axisLinear: {
    girdClosed: true,
    gridConnect: 'arc',
    gridDirection: 'negative',
    gridType: 'surround',
    titlePosition: 'top',
    titleSpacing: 0,
  },
  axisArc: {
    title: false,
    titlePosition: 'inner',
    line: false,
    tick: true,
    labelSpacing: 4,
  },
  axisRadar: {
    girdClosed: true,
    gridStrokeOpacity: 0.3,
    gridType: 'surround',
    label: false,
    tick: false,
    titlePosition: 'start',
  },
  legendCategory: {
    backgroundFill: 'transparent',
    itemBackgroundFill: 'transparent',
    itemLabelFill: '#1D2129',
    itemLabelFillOpacity: 0.9,
    itemLabelFontSize: 12,
    itemLabelFontWeight: 'normal',
    itemMarkerFillOpacity: 1,
    itemMarkerSize: 8,
    itemSpacing: [8, 8],
    itemValueFill: '#1D2129',
    itemValueFillOpacity: 0.65,
    itemValueFontSize: 12,
    itemValueFontWeight: 'normal',
    navButtonFill: '#1D2129',
    navButtonFillOpacity: 0.65,
    navPageNumFill: '#1D2129',
    navPageNumFillOpacity: 0.45,
    navPageNumFontSize: 12,
    padding: 8,
    title: false,
    titleFill: '#1D2129',
    titleFillOpacity: 0.65,
    titleFontSize: 12,
    titleFontWeight: 'normal',
    titleSpacing: 4,
    tickStroke: '#1D2129',
    tickStrokeOpacity: 0.25,
    rowPadding: 8,
    colPadding: 12,
    maxRows: 3,
    maxCols: 3,
  },
  legendContinuous: {
    handleHeight: 12,
    handleLabelFill: '#1D2129',
    handleLabelFillOpacity: 0.45,
    handleLabelFontSize: 12,
    handleLabelFontWeight: 'normal',
    handleMarkerFill: '#1D2129',
    handleMarkerFillOpacity: 0.6,
    handleMarkerLineWidth: 1,
    handleMarkerStroke: '#1D2129',
    handleMarkerStrokeOpacity: 0.25,
    handleWidth: 10,
    labelFill: '#1D2129',
    labelFillOpacity: 0.45,
    labelFontSize: 12,
    labelFontWeight: 'normal',
    labelSpacing: 3,
    tick: true,
    tickLength: 12,
    ribbonSize: 12,
    ribbonFill: '#aaa',
    handle: true,
    handleLabel: false,
    handleShape: 'slider',
    handleIconSize: 6.666666666666666,
    indicator: false,
    titleFontSize: 12,
    titleSpacing: 4,
    titleFontWeight: 'normal',
    titleFillOpacity: 0.9,
    tickStroke: '#1D2129',
    tickStrokeOpacity: 0.45,
  },
  label: {
    fill: '#1D2129',
    fillOpacity: 0.65,
    fontSize: 12,
    fontWeight: 'normal',
    offset: 12,
    connectorStroke: '#1D2129',
    connectorStrokeOpacity: 0.45,
    connectorLineWidth: 1,
    connectorLength: 12,
    connectorLength2: 8,
    connectorDistance: 4,
  },
  innerLabel: {
    fill: '#ffffff',
    fontSize: 12,
    fillOpacity: 0.85,
    fontWeight: 'normal',
    offset: 0,
  },
  htmlLabel: {
    fontSize: 12,
    opacity: 0.65,
    color: '#1D2129',
    fontWeight: 'normal',
  },
  slider: {
    trackSize: 16,
    trackFill: '#416180',
    trackFillOpacity: 1,
    selectionFill: '#1783FF',
    selectionFillOpacity: 0.15,
    handleIconSize: 10,
    handleIconFill: '#f7f7f7',
    handleIconFillOpacity: 1,
    handleIconStroke: '#1D2129',
    handleIconStrokeOpacity: 0.25,
    handleIconLineWidth: 1,
    handleIconRadius: 2,
    handleLabelFill: '#1D2129',
    handleLabelFillOpacity: 0.45,
    handleLabelFontSize: 12,
    handleLabelFontWeight: 'normal',
  },
  scrollbar: {
    padding: [0, 0, 0, 0],
    trackSize: 6,
    isRound: true,
    slidable: true,
    scrollable: true,
    trackFill: '#e5e5e5',
    trackFillOpacity: 0,
    thumbFill: '#000',
    thumbFillOpacity: 0.15,
    thumbHighlightedFillOpacity: 0.2,
  },
  title: {
    spacing: 8,
    titleFill: '#1D2129',
    titleFillOpacity: 0.9,
    titleFontSize: 16,
    titleFontWeight: 'bold',
    titleTextBaseline: 'top',
    subtitleFill: '#1D2129',
    subtitleFillOpacity: 0.65,
    subtitleFontSize: 12,
    subtitleFontWeight: 'normal',
    subtitleTextBaseline: 'top',
  },
  tooltip: { css: { '.g2-tooltip': { 'font-family': 'sans-serif' } } },
} as const;

/**
 *
 * agent 模式的图表主题
 * @returns
 */
function AgentTheme() {
  const light = Light();
  return { ...light, ...theme };
}

register('theme.agent', AgentTheme);

export * from './Bar';
export * from './Pie';

export * from './Area';
export * from './Column';
export * from './Line';
